spring:
  # 环境配置 : dev:开发环境 , test:测试环境 , prod:生产环境
  profiles:
    active: test

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: dbState
      logic-delete-value: 0
      logic-not-delete-value: 1
