jwt:
  signature:
    secretkey: 8db801f3edf24d318f7bba30420e0b61

spring:
  # 环境配置 : dev:开发环境 , test:测试环境 , prod:生产环境
  profiles:
    active: dev

  # 国际化资源配置
  messages:
    basename: i18n/ValidationMessages , i18n/error_code
    encoding: UTF-8

  # Redis 缓存配置
  redis:
    host: 127.0.0.1
    port: 6379

  # Spring-MVC 配置
  mvc:
    # 屏蔽 Springboot 默认的一些错误处理,出现异常向外抛给 Advisor 进行处理
    throw-exception-if-no-handler-found: true

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: dbState
      logic-delete-value: 0
      logic-not-delete-value: 1
